# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rich Armstrong
email: heyricharmstrong@gmail.com
tagline: Multidisciplinary artist
description: "The online portfolio of multidisciplinary artist Rich Armstrong."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.richarmstrong.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: richarmstr_ong
github_username: radrich
# fathom_analytics: WBBMJNFH
logo: /assets/favicon-72.png

social:
  links:
    - https://twitter.com/richarmstr_ong
    - https://www.linkedin.com/in/heyricharmstrong
    - https://github.com/radrich
    - https://instagram.com/richarmstr_ong
    - https://dribbble.com/richarmstr_ong
    - https://behance.com/richarmstr_ong

twitter:
  username: richarmstr_ong
  card: summary

permalink: /:slug/

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "richarmstrong"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "richarmstrong"
      auto_related: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "richarmstrong"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      author: "richarmstrong"
      permalink: /:basename/
      
sass:
  sass_dir: _sass
  style: compressed

asset_version: 56

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
  slug_mode: default

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _redirects

# this means to ignore newlines until "baseurl:"
# >-
